$ANSIBLE_VAULT;1.1;AES256
32306161363166356431656532326139643566663262396362623137303464376462326261363835
6666646430643338333837383938383162303465396135340a356665376364373135656362333764
61643861313530666639386561646136353238386161326530333036373363343966363238653064
6264386235373164370a373561393739376536656634663132653263386631363862643565363330
66356233313062303364313130303536383130353833373730643534366531363731636531383436
32333762653837343663396332333730623362643235333865656462353733616537383632353939
38643139306333643534626464616335613337356263623436633231633036386231316461376436
66316631383965303839623636646231313534356462383564316234363266613361336132353763
33336332633561323761383730623630383564323536656165333165386265306230346436633835
3439373664376165303063346366653366663564663039313762
