$ANSIBLE_VAULT;1.1;AES256
66326163383435383534626665663037356139643135386164663731646336353530633938323165
6435373730623862626463353236613531306238643137300a323933613230343638393265303133
36326536623036303665336435363835373964653833623565316662653339313332653538336261
6632376266376536330a326461323837326231386536376462356136336464623665323134646262
63653164633032623531643639643538336239346664376661656261613731373763356239353963
64316436376437313665303634306633653534376532653966626231383437353666643961646364
62336232363230333563353535633364323230653931303332396239643137306362613137386133
31363333383866346639
