$ANSIBLE_VAULT;1.1;AES256
39616663616566636531393963353566643434363139366531343632386661373561303038383263
6639626365383865353932356634633761333238653337300a323163643831656262343335336436
32383731326431303732613363333335363666613831323832313066623364643961366165373266
3236333235326333660a653435613661633663333864303330633731313539376237373536313239
63373537343038343062393761643564303536366239646233383762343137383036353863323539
63323135353262373538636338363061356563373430306130633066636436613536313734643430
38666266303433336539336533646164663737616666616464313336356137386236386130303462
66393264376638346339
